---

- name: Install common packages
  apt:  name={{item}} state=installed
  with_items:
     - git
     - python-pip
     - gcc
     - tree
  become: yes
  become_method: sudo
- name: Python modules
  pip: name={{item}} state=latest
  with_items:
     - virtualenv
     - virtualenvwrapper
     - ipython
  become: yes
  become_method: sudo
